# Postgre deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:13.1
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: reviewfilmes
        - name: POSTGRES_PASSWORD
          value: Passw0rd!
        - name: POSTGRES_DB
          value: reviewfilmes
---
# Service postgre
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
# Web app deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewfilmes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reviewfilmes
  template:
    metadata:
      labels:
        app: reviewfilmes
    spec:
      containers:
      - name: reviewfilmes
        image: andrepreira/review-films:v1
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_HTTP_PORT
            value: "8080"
          - name: ConnectionStrings__DefaultConnection
            value: "Host=postgre;Port=5432;Database=reviewfilmes;Username=reviewfilmes;Password=Passw0rd!;"

---
# Service web app
apiVersion: v1
kind: Service
metadata:
  name: reviewfilmes
spec:
  selector:
    app: reviewfilmes
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
